# Generated by Django 3.2.5 on 2023-01-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(blank=True),
        ),
    ]
