# Generated by Django 3.2.5 on 2023-01-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_user_is_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
