# Generated by Django 3.2.5 on 2023-01-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
