# Generated by Django 3.2.5 on 2023-01-04 09:12

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_upload_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to=pages.models.content_file_name),
        ),
    ]
