# Generated by Django 3.2.5 on 2023-01-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='pages.company'),
        ),
    ]
